# Generated by Django 4.1.4 on 2023-01-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_id', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('discount_price', models.PositiveIntegerField(default=0, editable=False)),
                ('price', models.PositiveIntegerField()),
                ('stock_status', models.BooleanField(blank=True, default=True, editable=False)),
                ('product_pic', models.ImageField(default='product.jpg', upload_to='products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopSection.category')),
            ],
        ),
    ]
